<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>Vaporworks</AssemblyName><Version>1.0.0</Version></PropertyGroup>
 <ItemGroup><ProjectReference Include="../Vapor.Licensing/Vapor.Licensing.csproj" /></ItemGroup>
</Project>
