<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>DemoControl</AssemblyName></PropertyGroup>
 <ItemGroup><ProjectReference Include="..\Vapor.Licensing\Vapor.Licensing.csproj"/></ItemGroup>
</Project>
